language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python3 -m unittest src.test.test.Image

# command to run tests
#script:
#  - cd src/test
#  - python3 tes



